version: '3'
services:
  app:
    image: nodeassignmentimage
    networks:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  backend:
